<?php

namespace FondOfSpryker\Yves\EnhancedEcommerceCategoryConnector;

use FondOfSpryker\Yves\EnhancedEcommerceCategoryConnector\Dependency\EnhancedEcommerceCategoryConnectorToCurrencyClientBridge;
use Spryker\Glue\Kernel\AbstractBundleDependencyProvider;
use Spryker\Glue\Kernel\Container;

class EnhancedEcommerceCategoryConnectorDependencyProvider extends AbstractBundleDependencyProvider
{
    public const CLIENT_CURRENCY = 'CLIENT_CURRENCY';

    /**
     * @param \Spryker\Glue\Kernel\Container $container
     *
     * @return \Spryker\Glue\Kernel\Container
     */
    public function provideDependencies(Container $container): Container
    {
        return parent::provideDependencies($container); // TODO: Change the autogenerated stub
    }

    /**
     * @param \Spryker\Glue\Kernel\Container $container
     *
     * @return \Spryker\Glue\Kernel\Container
     */
    protected function addCurrencyClient(Container $container): Container
    {
        $container->set(static::CLIENT_CURRENCY, function (Container $container) {
            new EnhancedEcommerceCategoryConnectorToCurrencyClientBridge(
                $container->getLocator()->currency()->client()
            );
        });

        return $container;
    }
}
